apiVersion: v1
kind: Service
metadata:
  name: apache-orange
  annotations:
   avi_proxy: |
      {
        "virtualservice":{
          "analytics_policy":{
            "client_insights":"NO_INSIGHTS",
            "metrics_realtime_update":{
              "duration":0,
              "enabled":true
            },
            "full_client_logs":{
              "duration":0,
              "enabled":true
            }
          }
        },
        "pool":{
          "analytics_policy":{
            "enable_realtime_metrics":true
          }
        }
      }
spec:
  type: LoadBalancer
  ports:
  - name: http 
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: apache-orange
